server:
  port: 0

spring:
  application:
    name: user-service
  output:
    ansi.enabled: always
  h2:
    console:
      enable: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka : true
    fetch-registry: true
    service-url :
      defaultZoen: http://127.0.0.1:8761/eureka

greeting:
  message: Welcome to the Simple Mega-Ecommerce.